# Generated by Django 5.1.6 on 2025-04-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leisureProjects', '0002_profile_email_profile_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wallpaper',
            field=models.CharField(choices=[('wallpaper1.jpg', 'Wallpaper 1'), ('wallpaper2.jpg', 'Wallpaper 2'), ('wallpaper3.jpg', 'Wallpaper 3'), ('wallpaper4.jpg', 'Wallpaper 4'), ('wallpaper5.jpg', 'Wallpaper 5')], default='wallpaper1.jpg', max_length=50),
        ),
    ]
