# Generated by Django 5.1.6 on 2025-04-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leisureProjects', '0003_project_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='wallpaper',
            field=models.CharField(choices=[('wallpaper1.jpg', 'Wallpaper 1'), ('wallpaper2.jpg', 'Wallpaper 2'), ('wallpaper3.jpg', 'Wallpaper 3'), ('wallpaper4.jpg', 'Wallpaper 4'), ('wallpaper5.jpg', 'Wallpaper 5'), ('wallpaper6.jpg', 'Wallpaper 6'), ('wallpaper7.jpg', 'Wallpaper 6'), ('wallpaper8.jpg', 'Wallpaper 6')], default='wallpaper1.jpg', max_length=50),
        ),
    ]
