# Generated by Django 5.1.6 on 2025-04-07 16:41

from django.db import migrations

def migrate_roles(apps, schema_editor):
    Profile = apps.get_model('leisureProjects', 'Profile')
    # Convert solo -> user
    Profile.objects.filter(role='solo').update(role='user')
    # Convert team -> premium
    Profile.objects.filter(role='team').update(role='premium')
    # organizer remains unchanged

class Migration(migrations.Migration):
    dependencies = [
        ('leisureProjects', '0004_task_due_date_alter_project_wallpaper'),
    ]

    operations = [
        migrations.RunPython(migrate_roles),
    ]
