# Generated by Django 5.1.6 on 2025-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leisureProjects', '0007_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='wallpaper',
            field=models.CharField(choices=[('wallpaper1.jpg', 'Wallpaper 1'), ('wallpaper2.jpg', 'Wallpaper 2'), ('wallpaper3.jpg', 'Wallpaper 3'), ('wallpaper4.jpg', 'Wallpaper 4'), ('wallpaper5.jpg', 'Wallpaper 5'), ('wallpaper6.jpg', 'Wallpaper 6'), ('wallpaper7.jpg', 'Wallpaper 6'), ('wallpaper8.jpg', 'Wallpaper 6')], default='wallpaper1.jpg', max_length=50),
        ),
    ]
