# Generated by Django 5.1.6 on 2025-04-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leisureProjects', '0009_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
    ]
