# Generated by Django 5.1.6 on 2025-04-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leisureProjects', '0012_challengereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeTask',
        ),
    ]
