# Generated by Django 5.1.6 on 2025-04-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leisureProjects', '0015_moodrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodrating',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leisureProjects.project'),
        ),
        migrations.AddField(
            model_name='moodrating',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leisureProjects.task'),
        ),
    ]
