# Generated by Django 5.1.6 on 2025-04-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leisureProjects', '0016_moodrating_project_moodrating_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
